#pragma once

#include "BoxColliderComponent.hh"
#include "ButtonComponent.hh"
#include "CameraComponent.hh"
#include "DynamicComponent.hh"
#include "LightComponent.hh"
#include "NameComponent.hh"
#include "ParticleEmitterComponent.hh"
#include "RenderComponent.hh"
#include "RigidBodyComponent.hh"
#include "ScriptComponent.hh"
#include "SphereColliderComponent.hh"
#include "TextComponent.hh"
#include "TransformComponent.hh"
#include "UiComponent.hh"
